"""Generate Supabase / Postgres CREATE TABLE DDL from gold parquet schemas.

Run after Phase 2 (gold layer built). Output: output/create_tables.sql

Usage:
    python gen_supabase_ddl.py
    python gen_supabase_ddl.py --schema gold --drop  # adds DROP TABLE IF EXISTS

Pandas dtype → Postgres mapping:
    int64        → bigint
    int32        → integer
    float64      → double precision
    bool         → boolean
    object       → text
    datetime64   → timestamp
"""
from __future__ import annotations

import argparse
import re
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).parent
GOLD = ROOT / "output" / "gold"
OUT_SQL = ROOT / "output" / "create_tables.sql"

DTYPE_MAP = {
    "int64":          "bigint",
    "Int64":          "bigint",
    "int32":          "integer",
    "int16":          "smallint",
    "float64":        "double precision",
    "float32":        "real",
    "bool":           "boolean",
    "object":         "text",
    "datetime64[ns]": "timestamp",
}


def pg_type(dtype: str, col_name: str) -> str:
    s = str(dtype)
    if "datetime" in s.lower():
        return "timestamptz" if "UTC" in s or "tz" in s else "timestamp"
    if s in DTYPE_MAP:
        return DTYPE_MAP[s]
    # Heuristic by name
    n = col_name.lower()
    if n.endswith("_dkk") or n.endswith("_pct") or n.endswith("_rate"):
        return "numeric(18,2)"
    if n.endswith("_key") or n.endswith("_id") or n in ("year", "month", "quarter", "day", "headcount"):
        return "bigint"
    return "text"


def sanitize_col(name: str) -> str:
    """Postgres-safe quoted identifier; preserves case via double-quotes."""
    return '"' + name.replace('"', '""') + '"'


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--schema", default="public", help="Postgres schema name (default: public)")
    ap.add_argument("--drop", action="store_true", help="Prepend DROP TABLE IF EXISTS")
    ap.add_argument("--prefix", default="gold_", help="Table name prefix (default: gold_)")
    args = ap.parse_args()

    parquets = sorted(GOLD.glob("*.parquet"))
    if not parquets:
        raise SystemExit(f"No parquet files in {GOLD}. Run the pipeline first.")

    lines: list[str] = []
    lines.append(f"-- Auto-generated by gen_supabase_ddl.py from {len(parquets)} gold parquet files")
    lines.append(f"-- Schema: {args.schema}")
    lines.append("")
    lines.append(f"CREATE SCHEMA IF NOT EXISTS {args.schema};")
    lines.append("")

    for pq in parquets:
        df = pd.read_parquet(pq)
        table_name = f"{args.prefix}{pq.stem}"
        full = f"{args.schema}.{sanitize_col(table_name)}"

        if args.drop:
            lines.append(f"DROP TABLE IF EXISTS {full} CASCADE;")

        lines.append(f"CREATE TABLE IF NOT EXISTS {full} (")
        col_lines: list[str] = []
        pk_candidates: list[str] = []
        for c in df.columns:
            t = pg_type(df[c].dtype, c)
            col_lines.append(f"    {sanitize_col(c)} {t}")
            # Detect primary key candidate (ends in _id or _key and is unique)
            cl = c.lower()
            if (cl.endswith("_id") or cl.endswith("_key")) and df[c].is_unique:
                pk_candidates.append(c)
        lines.append(",\n".join(col_lines))
        lines.append(");")

        # Indexes on key columns
        for c in df.columns:
            cl = c.lower()
            if cl.endswith("_key") or cl.endswith("_id") or cl == "date_key":
                idx_name = f"idx_{table_name}_{c}"
                lines.append(f"CREATE INDEX IF NOT EXISTS {sanitize_col(idx_name)} ON {full} ({sanitize_col(c)});")

        # Primary key — pick first unique _id/_key column if exactly one
        if len(pk_candidates) == 1:
            pk = pk_candidates[0]
            lines.append(
                f"ALTER TABLE {full} "
                f"ADD CONSTRAINT pk_{table_name} PRIMARY KEY ({sanitize_col(pk)});"
            )
        lines.append("")

    OUT_SQL.parent.mkdir(parents=True, exist_ok=True)
    OUT_SQL.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT_SQL.relative_to(ROOT)} -- {len(parquets)} tables")
    print(f"\nNext: open Supabase SQL editor -> paste contents -> Run.")
    print(f"    cat {OUT_SQL.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
